# -*- coding: utf-8 -*-
"""evolve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Orh9Adgp-bUcaOM7qCYMdjeYZHQXSyJq
"""

!pip install transformers torch biopython pandas

import torch
from transformers import AutoTokenizer, EsmForMaskedLM
from Bio import pairwise2
from Bio.Align import substitution_matrices
import pandas as pd

# --- SCIENTIFIC SEQUENCES ---
# DtpA (E. coli) - UniProt: P75743
dtpa_seq = "MSTANQKPTESVSLNAFKQPKAFYLIFSIELWERFGYYGLQGIMAVYLVKQLGMSEADSITLFSSFSALVYGLVAIGGWLGDKVLGTKRVIMLGAIVLAIGYTLVAWSGHDAGIVYMGMAAIAVGNGLFKANPSSLLSTCYEKNDPRLDGAFTMYYMSVNIGSFFSMIATPWLAAKYGWSVAFALSVVGLLITIVNFAFCQRWVKQYGSKPDFEPINYRNLLLTIIGVVALIAIATWLLHNQEVARMALGVVAFGIVVIFGKEAFAMKGAARRKMIVAFILMLEAIIFFVLYSQMPTSLNFFAIRNVEHSILGLAVEPEQYQALNPFWIIIGSPILAAIYNKMGDTLPMPTKFAIGMVMCSGAFLILPLGAKFASDAGIVSVSWLVASYGLQSIGELMISGLGLAMVAQLVPQRLMGFIMGSWFLTTAGANLIGGYVAGMMAVPDNVTDPLMSLEVYGRVFLQIGVATAVIAVLMLLTAPKLHRMTQDDAADKAAKAAVA" # Use full UniProt: Q5KWA5
# Human PepT1 (Target - SLC15A1)
 # Replace with full P75743 FASTA
# Human PepT1 - UniProt: P46059
hpept1_seq = "MGMSKSHSFFGYPLSIFFIVVNEFCERFSYYGMRAILILYFTNFISWDDNLSTAIYHTFVALCYLTPILGALIADSWLGKFKTIVSLSIVYTIGQAVTSVSSINDLTDHNHDGTPDSLPVHVVLSLIGLALIALGTGGIKPCVSAFGGDQFEEGQEKQRNRFFSIFYLAINAGSLLSTIITPMLRVQQCGIHSKQACYPLAFGVPAALMAVALIVFVLGSGMYKKFKPQGNIMGKVAKCIGFAIKNRFRHRSKAFPKREHWLDWAKEKYDERLISQIKMVTRVMFLYIPLPMFWALFDQQGSRWTLQATTMSGKIGALEIQPDQMQTVNAILIVIMVPIFDAVLYPLIAKCGFNFTSLKKMAVGMVLASMAFVVAAIVQVEIDKTLPVFPKGNEVQIKVLNIGNNTMNISLPGEMVTLGPMSQTNAFMTFDVNKLTRINISSPGSPVTAVTDDFKQGQRHTLLVWAPNHYQVVKDGLNQKPEKGENGIRFVNTFNELITITMSGKVYANISSYNASTYQFFPSGIKGFTISSTEIPPQCQPNFNTFYLEFGSAYTYIVQRKNDSCPEVKVFEDISANTVNMALQIPQYFLLTCGEVVFSVTGLEFSYSQAPSNMKSVLQAGWLLTVAVGNIIVLIVAGAGQFSKQWAEYILFAALLLVVCVVFAIMARFYTYINPAEIEAQFDEDEKKNRLEKSNPYFMSGANSQKQM" # Replace with full P46059 FASTA

# --- 1. SEQUENCE ALIGNMENT ---
# Using BLOSUM62 to find evolutionary equivalents
matrix = substitution_matrices.load("BLOSUM62")
alignments = pairwise2.align.globalds(dtpa_seq, hpept1_seq, matrix, -10, -0.5)
aln_dtpa, aln_hu, score, _, _ = alignments[0]

# --- 2. BINDING POCKET MAPPING ---
# Key residues in Human PepT1 known for drug binding
# (e.g., Y167, W294, E595)
human_pocket = [24, 26, 27, 34, 56, 57, 64, 91, 140, 162, 166, 167, 171, 282, 294, 297, 328, 341, 594]
targets = []
hu_idx = 0
for i, (r_dtpa, r_hu) in enumerate(zip(aln_dtpa, aln_hu)):
    if r_hu != '-': hu_idx += 1
    if hu_idx in human_pocket and r_dtpa != '-':
        dtpa_pos = i - aln_dtpa[:i].count('-')
        targets.append({'pos': dtpa_pos, 'hu_res': r_hu, 'dtpa_res': r_dtpa})

# --- 3. ESM-2 STABILITY SCORING ---
model_name = "facebook/esm2_t33_650M_UR50D"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = EsmForMaskedLM.from_pretrained(model_name)
model.eval()

def get_fitness(seq, pos, mutant_res):
    inputs = tokenizer(seq, return_tensors="pt")
    with torch.no_grad():
        logits = model(**inputs).logits
    probs = torch.nn.functional.softmax(logits, dim=-1)
    token_id = tokenizer.encode(mutant_res, add_special_tokens=False)[0]
    return probs[0, pos + 1, token_id].item()

# --- 4. EXECUTION ---
print(f"Scientific Alignment Score: {score}")
results = []
for t in targets:
    fitness = get_fitness(dtpa_seq, t['pos'], t['hu_res'])
    results.append({
        'DtpA_Site': f"{t['dtpa_res']}{t['pos']}",
        'Human_Residue': t['hu_res'],
        'Stability_Score': fitness
    })

print(pd.DataFrame(results))

import torch
from transformers import AutoTokenizer, EsmForMaskedLM
import pandas as pd

# 1. Initialize the ESM-2 PLM
model_name = "facebook/esm2_t33_650M_UR50D"
print(f"Loading {model_name}...")
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = EsmForMaskedLM.from_pretrained(model_name)
model.eval()

if torch.cuda.is_available():
    model = model.to("cuda")

def get_fitness(sequence, target_pos, target_aa):
    """Calculates the PLM probability of an amino acid at a target position."""
    inputs = tokenizer(sequence, return_tensors="pt")
    if torch.cuda.is_available():
        inputs = {k: v.to("cuda") for k, v in inputs.items()}

    with torch.no_grad():
        logits = model(**inputs).logits

    probs = torch.nn.functional.softmax(logits, dim=-1)
    token_id = tokenizer.encode(target_aa, add_special_tokens=False)[0]
    return probs[0, target_pos + 1, token_id].item()

def find_epistatic_rescue(base_seq, primary_pos, primary_mut, search_range=3):
    """Sweeps neighboring residues to find a secondary mutation that improves stability."""
    seq_list = list(base_seq)
    seq_list[primary_pos] = primary_mut
    single_mutant_seq = "".join(seq_list)

    baseline_score = get_fitness(single_mutant_seq, primary_pos, primary_mut)

    amino_acids = "ACDEFGHIKLMNPQRSTVWY"
    best_rescue = None
    best_score = baseline_score

    start_search = max(0, primary_pos - search_range)
    end_search = min(len(base_seq), primary_pos + search_range + 1)

    for neighbor_pos in range(start_search, end_search):
        if neighbor_pos == primary_pos:
            continue

        original_neighbor_aa = single_mutant_seq[neighbor_pos]

        for aa in amino_acids:
            if aa == original_neighbor_aa:
                continue

            temp_list = list(single_mutant_seq)
            temp_list[neighbor_pos] = aa
            double_mutant_seq = "".join(temp_list)

            new_score = get_fitness(double_mutant_seq, primary_pos, primary_mut)

            if new_score > best_score:
                best_score = new_score
                best_rescue = {
                    'Secondary_Mutation': f"{original_neighbor_aa}{neighbor_pos+1}{aa}",
                    'New_Stability_Score': new_score,
                    'Improvement_Factor': new_score / baseline_score
                }

    return best_rescue

# --- EXECUTE THE EXPERIMENT ---
# Full DtpA Wild-Type Sequence
dtpa_seq = "MSTANQKPTESVSLNAFKQPKAFYLIFSIELWERFGYYGLQGIMAVYLVKQLGMSEADSITLFSSFSALVYGLVAIGGWLGDKVLGTKRVIMLGAIVLAIGYTLVAWSGHDAGIVYMGMAAIAVGNGLFKANPSSLLSTCYEKNDPRLDGAFTMYYMSVNIGSFFSMIATPWLAAKYGWSVAFALSVVGLLITIVNFAFCQRWVKQYGSKPDFEPINYRNLLLTIIGVVALIAIATWLLHNQEVARMALGVVAFGIVVIFGKEAFAMKGAARRKMIVAFILMLEAIIFFVLYSQMPTSLNFFAIRNVEHSILGLAVEPEQYQALNPFWIIIGSPILAAIYNKMGDTLPMPTKFAIGMVMCSGAFLILPLGAKFASDAGIVSVSWLVASYGLQSIGELMISGLGLAMVAQLVPQRLMGFIMGSWFLTTAGANLIGGYVAGMMAVPDNVTDPLMSLEVYGRVFLQIGVATAVIAVLMLLTAPKLHRMTQDDAADKAAKAAVA"

# Your risky targets (0-indexed for Python: Position - 1)
risky_targets = [
    {'name': 'S64H', 'pos': 63, 'mut': 'H'},
    {'name': 'L98Y', 'pos': 97, 'mut': 'Y'},
    {'name': 'A285R', 'pos': 284, 'mut': 'R'},
    {'name': 'F302W', 'pos': 301, 'mut': 'W'},
    {'name': 'R305F', 'pos': 304, 'mut': 'F'},
    {'name': 'A337D', 'pos': 336, 'mut': 'D'}
]

print("\nRunning Epistatic Rescue Sweep...")
final_results = []

for target in risky_targets:
    print(f"Analyzing {target['name']}...")
    rescue_data = find_epistatic_rescue(dtpa_seq, target['pos'], target['mut'], search_range=3)

    if rescue_data:
        final_results.append({
            'Target_Site': target['name'],
            'Best_Rescue_Mutation': rescue_data['Secondary_Mutation'],
            'New_Score': f"{rescue_data['New_Stability_Score']:.2e}",
            'Fold_Improvement': f"{rescue_data['Improvement_Factor']:.1f}x"
        })
    else:
        final_results.append({
            'Target_Site': target['name'],
            'Best_Rescue_Mutation': "None found in range",
            'New_Score': "N/A",
            'Fold_Improvement': "N/A"
        })

df_final = pd.DataFrame(final_results)
print("\n--- EPISTATIC RESCUE RESULTS ---")
print(df_final.to_string(index=False))